### ISSUE TITLE
task_cgo.go: fail build if MK version is not the expected one

### ISSUE THREAD

**Issue by hellais** [ooni/probe-engine#315] opened 2020-02-06 11:56 UTC
When running the websites test this appears in the output:
```
Found backend option which is not mapped as a valid option. We will continue processing
Found no_geoip option which is not mapped as a valid option. We will continue processing
Found no_resolver_lookup option which is not mapped as a valid option. We will continue processing
Skipping bouncer
```

This smells like an MK log output. @bassosimone do you think we should be concerned about this?

**Comment by bassosimone** [comment] 2020-02-15 12:08
@hellais what specific version of probe-cli you're referring to? The latest MK (v0.10.9) does not have this issue and I am wondering whether this version of probe-cli was instead linked against an old MK. I have v0.10.8 locally installed with homebrew and it also does not have this issue. (v0.10.9 is v0.10.8 with a fix in the build script that avoids a breakage caused by attempting to download MaxMind DB.)

**Comment by hellais** [comment] 2020-02-17 10:25
> what specific version of probe-cli you're referring to? The latest MK (v0.10.9) does not have this issue and I am wondering whether this version of probe-cli was instead linked against an old MK.

This was on OONI Probe Desktop v3.0.0-rc.4 on windows.

**Comment by bassosimone** [comment] 2020-02-17 10:31
@hellais thank you, let me take a look.

**Comment by bassosimone** [comment] 2020-02-17 10:42
@hellais I have run `ooniprobe show` and noticed that probe-cli v3.0.0-rc.9 is using MK v0.10.3, which strikes me as brew not being up to date before releasing. I've committed 4a9034d to master that mentions in Readme.md that we should update MK using brew. Even if my diagnosis is wrong, spelling that out on Readme.md won't hurt. Could you please check if the version of MK bundled with your ooniprobe-cli builds is old as I suspect? (Checking `/usr/local/Cellar/measurement-kit` and `/usr/local/Cellar/mingw-w64-measurement-kit` is probably a good enough proxy.) If that's the case, then we can safely close this issue. Otherwise more investigation is needed.

**Comment by bassosimone** [comment] 2020-02-17 10:50
So, the root cause is that the version of MK is too old, as confirmed by @hellais. The fix is to put some pre-processor checks inside of `measurementkit/task_cgo.go` such that the build fails if the version of MK that we're using in the local system is not the one we would expect.

**Comment by bassosimone** [comment] 2020-02-24 17:29
To implement this issue in a meaningful way, we need to implement https://github.com/ooni/probe-engine/issues/25 first. I will try to understand if (a subset of) that is doable.

**Closed** 2020-02-25 10:54 UTC
Labels: bug, effort/XS, ooni/probe-engine, priority/medium
