### ISSUE TITLE
Detect Signal Private Messenger blocking

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/probe-engine#124] opened 2019-11-26 14:29 UTC
https://signal.org/ is designed for privacy. Albeit low on popularity, it could be a prime target for blocking.

**Comment by hellais** [comment] 2019-11-26 15:46
This is duplicate of: https://github.com/ooni/spec/issues/149

**Comment by hellais** [comment] 2019-11-26 15:46
I guess we should move the ooni/spec issue in here.

**Comment by agrabeli** [comment] 2019-11-26 17:32
A Signal test has been requested by several community members multiple times over the last years.

**Comment by bassosimone** [comment] 2019-12-19 15:14
Yes, this is a duplicate and I will close this issue. We should see to avoid having too many repositories where issues could be opened, because dealing with dupes is not pleasant.

**Closed by bassosimone** 2019-12-19 15:14 UTC
Labels: duplicate, effort/XL, new experiment, priority/low
