### ISSUE TITLE
Disruption in connection with default probe services (ps{1,2}) in some crazy networks.

### ISSUE THREAD

**Issue by xhdix** [ooni/probe-engine#1173] opened 2021-01-08 14:48 UTC
In some crazy networks, backend communication does not work properly and requires a permanent change to CloudFront address as a probe-service in that test(s).

**Comment by bassosimone** [comment] 2021-02-01 10:59
Thank you for reporting this issue to us! It seems this is a less severe version of https://github.com/ooni/probe/issues/1324. The way to fix the issue your reported is easier than https://github.com/ooni/probe/issues/1324. The correct way of doing that seems to refactor the way in which `./probeservices` work.

Currently, `./probeservices` works as follows:

1. select the best probe service (which may also be CloudFront)
2. use it consistently

The problem you describe seems to be that the initial selection eventually stops working.

So, I think the correct fix is to make `./probeservices` works like this: for every required backend interaction, just try with the ordinary probe services and fallback to CloudFront in case of failure. I suspect this solution would not be optimal because it may be causing a bunch of timeouts and retries. So, I think there is _also_ a need to tweak the logic such that we don't waste much of our time waiting for timeouts to expire. That said, I think the first required step would be the above refactoring.

**Comment by xhdix** [comment] 2021-02-01 11:45
Great! Thanks. Also the situation is getting worse... Soon you also will need the ability to configure proxies in apps.

**Comment by bassosimone** [comment] 2021-03-15 11:02
I am going to mark this issue as a duplicate of https://github.com/ooni/probe/issues/1324. Technically, it's not exactly a duplicate, but the work required to fix the problem described here is the same work required to fix https://github.com/ooni/probe/issues/1324. As such, it makes my life easier to have a single umbrella issue for describing this kind of work. Thank you for opening the original issue and please keep monitoring https://github.com/ooni/probe/issues/1324 to see our progress towards a resolution!

**Closed** 2021-03-15 11:02 UTC
Labels: bug, duplicate, priority/high
